<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2018, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace ExpandOnline\Criteo;



class ApiExceptionErrorCode
{
    const NoError = 'NoError';
    const BadAuthentification = 'BadAuthentification';
    const AuthTokenExpired = 'AuthTokenExpired';
    const InvalidAppTokenAuthToken = 'InvalidAppTokenAuthToken';
    const AuthentificationNotExist = 'AuthentificationNotExist';
    const UserAccessDisabled = 'UserAccessDisabled';
    const UserAccessNotAllowed = 'UserAccessNotAllowed';
    const MissingData = 'MissingData';
    const OperationNotSupported = 'OperationNotSupported';
    const InvalidID = 'InvalidID';
    const AccessToThisJobNotAllowed = 'AccessToThisJobNotAllowed';
    const InvalidFieldValue = 'InvalidFieldValue';
    const UnexpectedError = 'UnexpectedError';
    const AppTokenNotSupportedForPartnerLogin = 'AppTokenNotSupportedForPartnerLogin';
}
