<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2018, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace ExpandOnline\Criteo;



class ReportColumn
{
    const clicks = 'clicks';
    const impressions = 'impressions';
    const ctr = 'ctr';
    const revcpc = 'revcpc';
    const ecpm = 'ecpm';
    const cost = 'cost';
    const sales = 'sales';
    const convRate = 'convRate';
    const orderValue = 'orderValue';
    const salesPostView = 'salesPostView';
    const convRatePostView = 'convRatePostView';
    const orderValuePostView = 'orderValuePostView';
    const costOfSale = 'costOfSale';
    const impressionWin = 'impressionWin';
    const costPerOrder = 'costPerOrder';
}
