<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2018, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace ExpandOnline\Criteo;



class campaign
{
    public $campaignID;
    // int
    public $campaignName;
    // string
    public $endDate;
    // string
    public $campaignBid;
    // bidInformation
    public $budgetID;
    // int
    public $remainingDays;
    // int
    public $status;
    // CampaignStatus
    public $categoryBids;
}
