<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2018, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace ExpandOnline\Criteo;



class ReportJob
{
    public $reportSelector;
    // ReportSelector
    public $reportType;
    // ReportType
    public $aggregationType;
    // AggregationType
    public $startDate;
    // string
    public $endDate;
    // string
    public $selectedColumns;
    // ArrayOfReportColumn
    public $isResultGzipped;
}
